---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Simple Checks"

on:
  workflow_call:

jobs:
  metadata-validation:
    name: Validate Image Metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
